openapi: 3.0.0
info:
  title: Fruits E-commerce API
  description: API for managing a fruits e-commerce platform Online
  version: 1.0.0
servers:
  - url: http://localhost:9090/api
paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '400':
          description: Bad request (Username exists, Email exists, Invalid role, or Invalid user data)
        '500':
          description: Internal server error (Failed to send email)

  /auth/login:
    post:
      summary: Login user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestDTO'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseDTO'
        '401':
          description: Unauthorized (User not found, Account locked, or Bad credentials)

  /auth/lock-user:
    post:
      summary: Lock a user account
      tags:
        - Authentication
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: identifier
          required: true
          schema:
            type: string
          description: Username or email of the user to lock
      responses:
        '200':
          description: User account locked successfully
        '400':
          description: Bad request (User not found or already locked)
        '403':
          description: Forbidden (Insufficient permissions)
        '500':
          description: Internal server error

  /auth/unlock-user:
    post:
      summary: Unlock a user account
      tags:
        - Authentication
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: identifier
          required: true
          schema:
            type: string
          description: Username or email of the user to unlock
      responses:
        '200':
          description: User account unlocked successfully
        '400':
          description: Bad request (User not found or not locked)
        '403':
          description: Forbidden (Insufficient permissions)
        '500':
          description: Internal server error

components:
  schemas:
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          example: "john_doe"
        email:
          type: string
          example: "john.doe@example.com"
        role:
          type: string
          example: "CLIENT"
    LoginRequestDTO:
      type: object
      properties:
        username:
          type: string
          example: "john_doe"
        password:
          type: string
          example: "password123"
    AuthResponseDTO:
      type: object
      properties:
        token:
          type: string
          example: "eyJhbGciOiJIUzUxMiIsInR..."
        expiresAt:
          type: string
          format: date-time
          example: "2024-09-23T23:59:59Z"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT